src/Entity/Actor.php
<?php

namespace App\Entity;

use App\Repository\ActorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Valab ;

/**
 * @ORM\Entity(repositoryClass=ActorRepository::class)
 */
class Actor
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Valab\Length(min=3,max=15,minMessage="il faut 3 caracteres",maxMessage="trop de caractere")
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    /**
     * @ORM\ManyToMany(targetEntity=Film::class, mappedBy="Actors")
     */
    private $films;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $wiki;

    public function __construct()
    {
        $this->films = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    /**
     * @return Collection|Film[]
     */
    public function getFilms(): Collection
    {
        return $this->films;
    }

    public function addFilm(Film $film): self
    {
        if (!$this->films->contains($film)) {
            $this->films[] = $film;
            $film->addActor($this);
        }

        return $this;
    }

    public function removeFilm(Film $film): self
    {
        if ($this->films->removeElement($film)) {
            $film->removeActor($this);
        }

        return $this;
    }

    public function getWiki(): ?string
    {
        return $this->wiki;
    }

    public function setWiki(?string $wiki): self
    {
        $this->wiki = $wiki;

        return $this;
    }
}

src/Form/ActorType.php
<?php

namespace App\Form;

use App\Entity\Actor;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ActorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('Prenom')
            ->add('Image')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Actor::class,
        ]);
    }
}

src/Controller/ActorController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Film ;
use App\Entity\Actor ;
use App\Repository\ActorRepository ;
use App\Form\ActorType ;

use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;

class ActorController extends AbstractController
{
    /**
     * @Route("/actor", name="actor")
     */
    public function index(ActorRepository $ar): Response
    {   
        $repository = $this->getDoctrine()->getRepository(Actor::class);
        $actors = $repository->findAll();
        return $this->render('actor/index.html.twig', [
            'actors' => $actors
            
        ]);
    }

/**
 * @Route("/afficheactor/{id}", name="afficheactor")
 */

 public function afficheUnActeur(ActorRepository  $ar,$id): Response 
 {
     
     $actor =  $ar->find($id);
     return $this->render('actor/afficheUn.html.twig',["actor"=>$actor,]);
 }

 /**
 * @Route("/modifactor/{id}", name="modifactor")
 * @Route("/creationactor", name="creationactor")
 */


 public function modifierActor(Actor $actor=null,Request $request, EntityManagerInterface $en ){
   
    if (!$actor ) {
        $actor = new Actor();
    
    }
   
   
    $form = $this->createForm(ActorType::class,$actor);

    $form->handleRequest($request);
    if ($form->isSubmitted() ) {
        $en->persist($actor) ;
        $en->flush();
        return $this->redirectToRoute('actor');
    }
    return $this->render('actor/modifactor.html.twig',[
        "actor"=>$actor,
        "form"=>$form->createView()]);
 }

}

templates/actor/afficheUn.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des acteurs{% endblock %}

{% block body %}


<img style="width:100px" src="{{ asset('images/' ~ actor.image)}}">
      <td> {{actor.Prenom}} {{actor.Nom}} <td>
          <h3>{{actor.wiki}}</h3>


      
      
        
    
{% endblock %}

templates/actor/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}acteurs{% endblock %}

{% block body %}

{% for a in actors %}

      
        <img style="width:100px" src="{{ asset('images/' ~ a.image)}}">
        <td> <a href="{{ path ('afficheactor', {'id': a.id}) }}">{{a.nom}}</a></td>
        <td>{{ a.prenom }}</td>
        <td>
         <a href="{{ path ('modifactor', {'id': a.id}) }}">
         modifier</a>
        </td>

        <td>
          
        
    {% endfor %}


    <br>

     <a href="{{ path ('creationactor') }}">
          creer un nouvel acteur </a>

{% endblock %}

templates/actor/modifActor.html.twig
{% extends 'base.html.twig' %}

{% block title %}new acteurs{% endblock %}

{% block body %}


<img style="width:100px" src="{{ asset('images/' ~ actor.image)}}">
      <h1> {{actor.Prenom}} {{actor.Nom}} </h1>
      {{ form_start(form) }}
         {{ form_widget(form) }}
         <input type="submit" value="enregistrer" >
       {{form_end(form)}} 
    
{% endblock %}